version: "3.4"
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.app
    entrypoint: /bin/sleep infinity
    working_dir: /usr/src/app
    volumes:
      - "../:/usr/src:cached"
      - "./rustacean-home:/home/rustacean/:cached"
    environment:
      - TERM=xterm-256color
      - TZ="Europe/Rome"